grpc-1.67: Depend on py3-supported-cython instead of cpython
Without py3.13-cython, the build will fail once we add python3.13
support with errors like:

  src/python/grpcio/grpc/_cython/cygrpc.cpp: In function 'void __Pyx_init_assertions_enabled()':
  src/python/grpcio/grpc/_cython/cygrpc.cpp:6399:39: error: '_PyInterpreterState_GetConfig' was not declared in this scope; did you mean 'PyInterpreterState_GetID'?
   6399 |     __pyx_assertions_enabled_flag = ! _PyInterpreterState_GetConfig(__Pyx_PyThreadState_Current->interp)->optimization_level;
        |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        |                                       PyInterpreterState_GetID

cython-0 and py3.12-cython currently contain overlapping files, so
we can't have both installed. grpc-1.67 builds fine w/o cython-0,
so let's just drop it.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>