fix failures on merge queues, this step is not required so lets make it optional
merege queues do not have an associated PR number so the comment step fails, i.e we see this
```
Error: No issue/pull request in input neither in current context.
```
Let's just ignore these failures

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>