prism: remove jsonpath bump as fixed upstream now, fix new compile error
this fixes

```
error TS2353: Object literal may only specify known properties, and '__bundled__' does not exist in type 'JSONSchema6 | JSONSchema7'
```

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>