airflow-3: downgrade flask to supported 2.2.5 (#58592)
Upstream does not support Flake 2.2.5+ [1], and this makes connexion
dependency to fail [2].

Failure log is shared below:

```
File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 999, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  from connexion import FlaskApi
File "/opt/airflow/lib/python3.12/site-packages/airflow/providers/fab/auth_manager/fab_auth_manager.py", line 27, in <module>
File "/opt/airflow/lib/python3.12/site-packages/connexion/__init__.py", line 32, in <module>
  from .apps.flask_app import FlaskApp
File "/opt/airflow/lib/python3.12/site-packages/connexion/apps/flask_app.py", line 153, in <module>
  class FlaskJSONEncoder(json.JSONEncoder):
AttributeError: module 'flask.json' has no attribute 'JSONEncoder'
```

Upstream is working to upgrade FAB to v5 [3], so we may have in the near
future support for Flask v3.
With the occasion, this commit adds a test specific to the Flask JSON
encoder.
Last but not least, no CVEs are added with this dependency downgrade.

References:
1. https://github.com/apache/airflow/issues/52509
2.
https://github.com/spec-first/connexion/issues/1699#issuecomment-1524042812
3. https://github.com/apache/airflow/pull/50960

Signed-off-by: Massimiliano Giovagnoli <massimiliano.giovagnoli@chainguard.dev>