Fix(mlflow): pip install .[auth] for missing dependencies (#43118)
Deployment logs - 
```
bash-5.2# kubectl logs deployment/mlflow-run -n mlflow --all-containers=true
Checking connection to mlflow-tracking:80
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
Connection error
Error from server (BadRequest): container "mlflow" in pod "mlflow-run-57779479dd-bw6p7" is waiting to start: PodInitializing
bash-5.2# kubectl logs deployment/mlflow-tracking -n mlflow --all-containers=true
Checking connection to mlflow-postgresql:5432
timeout reached before the port went into state "inuse"
timeout reached before the port went into state "inuse"
Connection success
Traceback (most recent call last):
  File "/usr/share/mlflow/lib/python3.13/site-packages/mlflow/server/auth/__init__.py", line 120, in <module>
    from flask_wtf.csrf import CSRFProtect
ModuleNotFoundError: No module named 'flask_wtf'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/share/mlflow/lib/python3.13/site-packages/mlflow/server/auth/__init__.py", line 122, in <module>
    raise ImportError(
    ...<2 lines>...
    ) from e
ImportError: The MLflow basic auth app requires the Flask-WTF package to perform CSRF validation. Please run `pip install mlflow[auth]` to install it.
Error from server (BadRequest): container "wait-for-s3" in pod "mlflow-tracking-6865fcdb7d-tbrk4" is waiting to start: PodInitializing
bash-5.2# 
```
`pip install .[auth]`, will install MLflow with its additional
dependencies (such as Flask-WTF) required for basic authentication.

---------

Signed-off-by: Aditvil-Dev <aditya.tirmanwar@chainguard.dev>