airflow - Add missing dependency on python3, fix test.
airflow has 'no-depends', so it didn't even know that it depends on
python3 (the venv's python3 has a dynamic depends on python)

> (venv) f206c35a9154:/# ldd /opt/airflow/venv/bin/python
>        linux-vdso.so.1 (0x00007ffc89361000)
>        libpython3.12.so.1.0 => not found
>        libc.so.6 => /lib/libc.so.6 (0x00007d072f5d1000)
>        /lib64/ld-linux-x86-64.so.2 (0x00007d072f7c2000)

I'm not actually sure how that ever worked.

Then, add HOME to test's environment fix a problem with
>
>  File "/opt/airflow/venv/lib/python3.12/site-packages/airflow/settings.py", line 238, in configure_orm
>     raise AirflowConfigException(
> airflow.exceptions.AirflowConfigException: Cannot use relative path: `sqlite:///~/airflow/airflow.db` to connect to sqlite. Please use absolute path such as `sqlite:////tmp/airflow.db`.
> ERROR: failed to test package. the test environment has been preserved:
>   workspace dir: /home/user/tmp/melange-workspace-2227873862