pdftk: fix build, now needs openjdk-8
fixes:

```
org.gradle.api.GradleException: Toolchain installation '/usr/lib/jvm/java-1.8-openjdk' does not provide the required capabilities: [JAVA_COMPILER]
```

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>