Move bump of netty
PR #37343 (da1effa048283f) explains why this change is made.

The druid service was showing stacktrace like:

 > Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/handler/ssl/SslContext
 >  at org.apache.druid.server.emitter.EmitterModule.configure(EmitterModule.java:78)
 >  at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
 >  at com.google.inject.spi.Elements.getElements(Elements.java:108)
 >  at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:213)
 >  at com.google.inject.AbstractModule.configure(AbstractModule.java:66)
 >  at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)

Such can be seen in the log dir in the *.stdout files such as 'router.log.stdout'.