zetasql: bump bazel version from bazel-6 to bazel-7
This is what upstream uses in their docker-based builds,
and seems to be required. With -6, the build fails with:

 ERROR: /home/build/.cache/bazel/_bazel_build/79a1bfc8c8b5b6a6d226b38d072f165b/external/llvm_toolchain/BUILD.bazel:161:18: in system_module_map rule @llvm_toolchain//:module-x86_64-linux:
 Traceback (most recent call last):
    File "/home/build/.cache/bazel/_bazel_build/79a1bfc8c8b5b6a6d226b38d072f165b/external/toolchains_llvm/toolchain/internal/system_module_map.bzl", line 57, column 29, in _system_module_map
        template_dict.add_joined(
 Error in add_joined: add_joined() got unexpected keyword argument 'allow_closure'

Note that this requires a bump in JDK versions because
our bazel-7 uses class file format 65. That requires
openjdk >= 21, so let's just bump to the latest stable.

Signed-off-by: dann frazier <dann.frazier@chainguard.dev>