Remove langchain-text-splitters installation
Removed the upgrade installation of langchain-text-splitters.
as its causing error while running 

ModuleNotFoundError: No module named 'langchain_core.memory'

Signed-off-by: Debasish Biswas <debasishbsws.dev@gmail.com>