py3-lxml: depend on libxml<2.15, to fix incompatibility (#66421)
Specifically, we currently see:
```
# python3.13 -c 'from lxml import etree'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    from lxml import etree
ImportError: /usr/lib/python3.13/site-packages/lxml/etree.cpython-313-x86_64-linux-gnu.so: undefined symbol: xmlSchematronFree
```