statsd - Add modules that statsd depends on
The request that triggered this was for proxy.js function
which would throw an error :

    Error: Cannot find module 'hashring'
    code: 'MODULE_NOT_FOUND',

We were not installing any of its dependencies, so this
adds both the production dependencies (only "generic-pool")
and the optional (modern-syslog, hashring, winser).