datadog-agent and datadog-agent-nvml: various fixes to work with latest
- add libpcap
- symlink so build avoids downloading libpcap and uses system lib
- regen dep bump patch
- build with python 3.12 as integration dependencies require it
	ERROR: Package 'datadog-slurm' requires a different Python: 3.11.11 not in '>=3.12'
- compile datadog-agent-nvml with python 3.12
- patch to disable gpu monitor as causing test failures, upstream issue tracked https://github.com/DataDog/datadog-agent/issues/32419

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>