php-fpm_exporter - fix ftbfs after upgrade to go 1.23
When go moved to 1.23 the result of 'go mod tidy' is different
than it was with 1.22, and the result was an error in
go bump like:

> running step "Bump go deps to a certain version"
> Running go mod tidy with go version '1.23.0' ...
> Error: Failed to running update.
> Error: package google.golang.org/protobuf with
>       version 'v1.33.0' is already at version v1.34.2

The 'go mod tidy' updates google.golang.org/protobuf
to sufficient version.