Revert "deno/2.6.1 package update (#76003)" (#76117)
This reverts commit c275329f8c05759d15b4dc93b3c07a9fa88a0683.

Failing with:

```
error: could not compile `deno` (bin "deno") due to 1 previous error; 1 warning emitted
```

Signed-off-by: Jon Johnson <jon.johnson@chainguard.dev>