py3-fabric - multi-version (#34625)
use of openssl-legacy-provider is to avoid the:

>  RuntimeError: OpenSSL 3.0's legacy provider failed to load. This is
>  a fatal error by default, but cryptography supports running without
>  legacy algorithms by setting the environment variable
>  CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you
>  have likely made a mistake with your OpenSSL configuration.

The use of test/populated-etc-passwd is to cover python 3.13.
os.getuid() requires. either USER set or user in /etc/passwd.

> ```
>  + fab --version
>  Traceback (most recent call last):
>    File "/usr/lib/python3.13/getpass.py", line 173, in getuser
>      return pwd.getpwuid(os.getuid())[0]
>             ~~~~~~~~~~~~^^^^^^^^^^^^^
>  KeyError: 'getpwuid(): uid not found: 1000'
> ```

py3-deprecated needed changing to not provide py3-Deprecated
at a specific version.