datadog-agent: various fixes to work with latest 7.60.0 update
Included:
- add libpcap
- symlink so build avoids downloading libpcap and uses system lib
- build with python 3.12 as integration dependencies require it
```
ERROR: Package 'datadog-slurm' requires a different Python: 3.11.11 not in '>=3.12'
```

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>