neo4j-2025.01: update to OpenJDK 21 to fix compilation error
Namely:

```
$ mvn package '-DskipTests=true' -T14C -q '-Doverwrite=true'
Security framework of XStream not explicitly initialized, using predefined black list on your own risk.
Security framework of XStream not explicitly initialized, using predefined black list on your own risk.
[ERROR] scalac error: '21' is not a valid choice for '-target'
[ERROR] scalac error: bad option: '-target:jvm-21'
[ERROR] scalac error: '21' is not a valid choice for '-target'
[ERROR] scalac error: bad option: '-target:jvm-21'
[ERROR] exception compilation error occurred!!!
```