remove patch since it breaks the app (#44523)
We were assuming that this patch could work but the app is failing with
the following error:

```bash
INFO: Setting the server's publish address to be http://0.0.0.0:9998/
Exception in thread "main" java.lang.NoSuchMethodError: 'int org.eclipse.jetty.util.URIUtil.getDefaultPortForScheme(java.lang.String)'
        at org.eclipse.jetty.http.HttpScheme.<init>(HttpScheme.java:45)
```

so this PR aims to fix this issue but there will be CVEs reported but we
are going to fill an advisory for the given CVE for the package.

Signed-off-by: Batuhan Apaydin <batuhan.apaydin@chainguard.dev>