py3-pluggy - resolve a dependency loop?
This seems to resolve a dependency loop that wolfictl complains about.

Without this change, `wolfictl text` as run in 'Determine packages to
test build' will fail like this:

    $ burl=https://packages.wolfi.dev/bootstrap/stage3
    $ wolfictl text --pipeline-dir=./pipelines \
        -r$burl -k$burl/wolfi-signing.rsa.pub   2>&1 |
         tee out.log

    2024/09/20 15:12:20 ERRO
      unresolvable cycle:
        py3-pygments:2.18.0-r1@local ->
        py3-supported-hatchling:1.25.0-r2@local,
      caused by:
        py3-supported-hatchling:1.25.0-r2@local ->
        py3-hatchling:1.25.0-r2@local ->
        git:2.46.1-r0@local ->
        curl-dev:8.10.1-r0@local ->
        libpsl-dev:0.21.5-r3@local ->
        libpsl:0.21.5-r3@local ->
        gtk-doc:1.34.0-r0@local ->
        py3-pygments:2.18.0-r1@local

    Error: unable to build graph:
       unable to re-add original edge with new dep still causes cycle
           gtk-doc:1.34.0-r0@local -> py3-supported-hatchling
       unable to build graph:
           unable to re-add original edge with new dep still causes cycle
           gtk-doc:1.34.0-r0@local -> py3-supported-hatchling