opensearch: build with Java 17 which is the same as upstream and use modified startup script to avoid duplicate env vars and system properties being used.
This prevents startup errors like
```
ERROR: setting [discovery.seed_hosts] already set, saw [opensearch-cluster-master-headless] and [opensearch-cluster-master-headless]
```

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>