font-xorg: make co-installable (#59263)
`font-xorg-dirs` is for to provide fonts.dir and fonts.scale common dirs
(using mkfontscale) across all of the font-xorg- packages, instead of
duplicate, everywhere, this is a common package

Fix for:

```
fc4079cb3b9d:/work/packages# apk add font-xorg
(1/25) Installing font-xorg-adobe100dpi (1.0.4-r0)
(2/25) Installing font-xorg-adobe75dpi (1.0.4-r0)
(3/25) Installing font-xorg-adobeutopia100dpi (1.0.5-r0)
ERROR: font-xorg-adobeutopia100dpi-1.0.5-r0: trying to overwrite usr/share/fonts/X11/100dpi/fonts.dir owned by font-xorg-adobe100dpi-1.0.4-r0.
(4/25) Installing font-xorg-adobeutopia75dpi (1.0.5-r0)
ERROR: font-xorg-adobeutopia75dpi-1.0.5-r0: trying to overwrite usr/share/fonts/X11/75dpi/fonts.dir owned by font-xorg-adobe75dpi-1.0.4-r0.
(5/25) Installing font-xorg-adobeutopiatype1 (1.0.5-r0)
(6/25) Installing font-xorg-arabicmisc (1.0.4-r0)
(7/25) Installing font-xorg-bh100dpi (1.0.4-r0)
ERROR: font-xorg-bh100dpi-1.0.4-r0: trying to overwrite usr/share/fonts/X11/100dpi/fonts.dir owned by font-xorg-adobe100dpi-1.0.4-r0.
(8/25) Installing font-xorg-bh75dpi (1.0.4-r0)
ERROR: font-xorg-bh75dpi-1.0.4-r0: trying to overwrite usr/share/fonts/X11/75dpi/fonts.dir owned by font-xorg-adobe75dpi-1.0.4-r0.
(9/25) Installing font-xorg-bhlucidatypewriter100dpi (1.0.4-r0)
ERROR: font-xorg-bhlucidatypewriter100dpi-1.0.4-r0: trying to overwrite usr/share/fonts/X11/100dpi/fonts.dir owned by font-xorg-adobe100dpi-1.0.4-r0.
(10/25) Installing font-xorg-bhlucidatypewriter75dpi (1.0.4-r0)
ERROR: font-xorg-bhlucidatypewriter75dpi-1.0.4-r0: trying to overwrite usr/share/fonts/X11/75dpi/fonts.dir owned by font-xorg-adobe75dpi-1.0.4-r0.
(11/25) Installing font-xorg-bhtype1 (1.0.4-r0)
ERROR: font-xorg-bhtype1-1.0.4-r0: trying to overwrite usr/share/fonts/X11/Type1/fonts.dir owned by font-xorg-adobeutopiatype1-1.0.5-r0.
ERROR: font-xorg-bhtype1-1.0.4-r0: trying to overwrite usr/share/fonts/X11/Type1/fonts.scale owned by font-xorg-adobeutopiatype1-1.0.5-r0.
(12/25) Installing font-xorg-bitstream100dpi (1.0.4-r0)
ERROR: font-xorg-bitstream100dpi-1.0.4-r0: trying to overwrite usr/share/fonts/X11/100dpi/fonts.dir owned by font-xorg-adobe100dpi-1.0.4-r0.
(13/25) Installing font-xorg-bitstreamtype1 (1.0.4-r0)
ERROR: font-xorg-bitstreamtype1-1.0.4-r0: trying to overwrite usr/share/fonts/X11/Type1/fonts.dir owned by font-xorg-adobeutopiatype1-1.0.5-r0.
ERROR: font-xorg-bitstreamtype1-1.0.4-r0: trying to overwrite usr/share/fonts/X11/Type1/fonts.scale owned by font-xorg-adobeutopiatype1-1.0.5-r0.
(14/25) Installing font-xorg-cursormisc (1.0.4-r0)
ERROR: font-xorg-cursormisc-1.0.4-r0: trying to overwrite usr/share/fonts/X11/misc/fonts.dir owned by font-xorg-arabicmisc-1.0.4-r0.
(15/25) Installing font-xorg-daewoomisc (1.0.4-r0)
ERROR: font-xorg-daewoomisc-1.0.4-r0: trying to overwrite usr/share/fonts/X11/misc/fonts.dir owned by font-xorg-arabicmisc-1.0.4-r0.
(16/25) Installing font-xorg-decmisc (1.0.4-r0)
ERROR: font-xorg-decmisc-1.0.4-r0: trying to overwrite usr/share/fonts/X11/misc/fonts.dir owned by font-xorg-arabicmisc-1.0.4-r0.
(17/25) Installing font-xorg-ibmtype1 (1.0.4-r0)
ERROR: font-xorg-ibmtype1-1.0.4-r0: trying to overwrite usr/share/fonts/X11/Type1/fonts.dir owned by font-xorg-adobeutopiatype1-1.0.5-r0.
ERROR: font-xorg-ibmtype1-1.0.4-r0: trying to overwrite usr/share/fonts/X11/Type1/fonts.scale owned by font-xorg-adobeutopiatype1-1.0.5-r0.
(18/25) Installing font-xorg-isasmisc (1.0.4-r0)
ERROR: font-xorg-isasmisc-1.0.4-r0: trying to overwrite usr/share/fonts/X11/misc/fonts.dir owned by font-xorg-arabicmisc-1.0.4-r0.
(19/25) Installing font-xorg-schumachermisc (1.1.3-r0)
ERROR: font-xorg-schumachermisc-1.1.3-r0: trying to overwrite usr/share/fonts/X11/misc/fonts.dir owned by font-xorg-arabicmisc-1.0.4-r0.
(20/25) Installing font-xorg-screencyrillic (1.0.5-r0)
(21/25) Installing font-xorg-sonymisc (1.0.4-r0)
ERROR: font-xorg-sonymisc-1.0.4-r0: trying to overwrite usr/share/fonts/X11/misc/fonts.dir owned by font-xorg-arabicmisc-1.0.4-r0.
(22/25) Installing font-xorg-sunmisc (1.0.4-r0)
ERROR: font-xorg-sunmisc-1.0.4-r0: trying to overwrite usr/share/fonts/X11/misc/fonts.dir owned by font-xorg-arabicmisc-1.0.4-r0.
(23/25) Installing font-xorg-winitzkicyrillic (1.0.4-r0)
ERROR: font-xorg-winitzkicyrillic-1.0.4-r0: trying to overwrite usr/share/fonts/X11/cyrillic/fonts.dir owned by font-xorg-screencyrillic-1.0.5-r0.
(24/25) Installing font-xorg-xfree86type1 (1.0.5-r0)
ERROR: font-xorg-xfree86type1-1.0.5-r0: trying to overwrite usr/share/fonts/X11/Type1/fonts.dir owned by font-xorg-adobeutopiatype1-1.0.5-r0.
ERROR: font-xorg-xfree86type1-1.0.5-r0: trying to overwrite usr/share/fonts/X11/Type1/fonts.scale owned by font-xorg-adobeutopiatype1-1.0.5-r0.
(25/25) Installing font-xorg (1-r0)
19 errors; 42 MiB in 40 packages
```

Example test:

```
82ce4bfb029e:/work/packages# apk add aarch64/font-xorg-adobeutopia100dpi-1.0.5-r1.apk 
(1/9) Installing libfontenc (1.1.8-r1)
(2/9) Installing libbrotlicommon1 (1.1.0-r5)
(3/9) Installing libbrotlidec1 (1.1.0-r5)
(4/9) Installing libbz2-1 (1.0.8-r18)
(5/9) Installing libpng (1.6.49-r0)
(6/9) Installing freetype (2.13.3-r1)
(7/9) Installing mkfontscale (1.2.3-r1)
(8/9) Installing font-xorg-dirs (1-r0)
(9/9) Installing font-xorg-adobeutopia100dpi (1.0.5-r1)
Executing busybox-1.37.0-r46.trigger
Executing mkfontscale-1.2.3-r1.trigger
Executing font-xorg-dirs-1-r0.trigger
OK: 17 MiB in 24 packages
82ce4bfb029e:/work/packages# apk add aarch64/font-xorg-adobeutopia75dpi-1.0.5-r1.apk 
(1/1) Installing font-xorg-adobeutopia75dpi (1.0.5-r1)
Executing mkfontscale-1.2.3-r1.trigger
Executing font-xorg-dirs-1-r0.trigger
OK: 18 MiB in 25 packages
```

Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>