binutils - do not ship gdbserver (#31000)
I installed gbd and saw this:

    $ apk add gdb
    (1/3) Installing bash (5.2.37-r1)
    (2/3) Installing gdb (15.2-r0)
ERROR: gdb-15.2-r0: trying to overwrite usr/bin/gdbserver owned by
binutils-2.43.1-r0.
ERROR: gdb-15.2-r0: trying to overwrite usr/lib/libinproctrace.so owned
by binutils-2.43.1-r0.
    (3/3) Downgrading binutils (2.43.1-r0 -> 2.42-r1)

For now, we are building gdb and binutils separate, so we do not want
them to conflict.

Other solutions exist, such as:
 * build gdbserver here and package it as its own thing
 * build gdb here and package things differently

This seemed like the easiest solution, and was the one that we had
before something changed in binutils between 2.42 and 2.43