bazel-8: disable repo_contents_cache to fix FTBFS on arm64
This fixes this error:

```
ERROR: The repo contents cache [/home/build/.cache/bazel/_bazel_root/cache/repos/v1/contents] is inside the workspace [/home/build]. This can cause spurious failures. Disable the repo contents cache with `--repo_contents_cache=`, or specify `--repo_contents_cache=<path outside the workspace>`.
```

I believe it doesn't appear on amd64 because that uses the QEMU runner
and `$HOME` is not `/home/build`.