Pin to use nodej-24 in order to fix FTBFS
When building with nodejs-25 we got the following error:

SecurityError: Cannot initialize local storage without a `--localstorage-file`   path

This was a change introduced in nodejs-25 and upstream will have to fix their code to be compatible with it

Signed-off-by: David Negreira <david.negreira@chainguard.dev>