fix(jitsucom-jitsu): upgrade nodejs-18 to nodejs-20
The rotor service crashes on startup with:

```
/app/main.js:369229
webidl.is.File = webidl.util.MakeTypeAssertion(File)
                                               ^

ReferenceError: File is not defined
    at 25510 (/app/main.js:369229:48)
    ...
Node.js v18.20.8
```

The `File` global was introduced in Node.js 20.

Signed-off-by: Francesco Bartolini <francesco.bartolini@chainguard.dev>


Export:  12d73fe0149476596a3e5f1530168f2e87e7eadd