bump openjdk-10 epoch to regenerate the APKINDEX as it is missing, the arm build failed on push to main
the build failure:
```
Copying file://./packages/aarch64/APKINDEX.tar.gz to gs://wolfi-production-registry-destination/os/aarch64/APKINDEX.tar.gz

ERROR: HTTPError 400: Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access
```

https://github.com/chainguard-images/images/actions/runs/4986356643/jobs/8933939069

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>