rustup: upgrade Rust toolchain to rust-1.95
The build was failing because enum-map@3.1.0 and enum-map-derive@1.0.1
(transitive dependencies of rustup 1.29.1) require rustc 1.95, but the
package was configured to use rust-1.94:

  error: rustc 1.94.1 is not supported by the following packages:
    enum-map@3.1.0 requires rustc 1.95
    enum-map-derive@1.0.1 requires rustc 1.95

Upgrade the build toolchain from rust-1.94 to rust-1.95 to satisfy
the minimum compiler version requirement.

Export:  b3e78bf591f0bd26fdac69541b47f7e8a95b8a75