switch to git-checkout, move away from setup.py as that has gone upstream
also set `SOURCE_DATE_EPOCH` env var to avoid build failure

```
ValueError: ZIP does not support timestamps before 1980
```

Signed-off-by: James Rawlings <jrawlings@chainguard.dev>