gobject-introspection - depend on py3-setuptools-73
gdk-pixbuf was found to be FTBFS, failing with a stacktrace like:

> Traceback (most recent call last):
>   File "/usr/bin/g-ir-scanner", line 103, in <module>
>     from giscanner.scannermain import scanner_main
>   File "/usr/lib/gobject-introspection/giscanner/scannermain.py", line 35, in <module>
>     from giscanner.ast import Include, Namespace
>   File "/usr/lib/gobject-introspection/giscanner/ast.py", line 27, in <module>
>     from .sourcescanner import CTYPE_TYPEDEF, CSYMBOL_TYPE_TYPEDEF
>   File "/usr/lib/gobject-introspection/giscanner/sourcescanner.py", line 25, in <module>
>     from .ccompiler import CCompiler
>   File "/usr/lib/gobject-introspection/giscanner/ccompiler.py", line 29, in <module>
>     from distutils.msvccompiler import MSVCCompiler
> ModuleNotFoundError: No module named 'distutils.msvccompiler'

This cherry-picks a upstream fix for the issue
 https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/515
from
https://gitlab.gnome.org/GNOME/gobject-introspection/-/merge_requests/490