wavefront-proxy: bump netty-bom and drop pombump netty-codec-http
The pombump of netty-codec-http causes stacktrace below, so
remove it.
Since we're here, go ahead and bump netty-bom to current version.

CorsConfig is deprecated in 4.1, but should still be present.
https://netty.io/4.1/api/io/netty/handler/codec/http/cors/CorsConfig.html

Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/handler/codec/http/cors/CorsConfig
    at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
    at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
    at java.base/java.lang.Class.getDeclaredMethod(Class.java:2473)
    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
    at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
    at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)