lychee: bump to 0.18.0 (#38813)
Upstream has been changed its tag naming, so it has `lychee-v` prefix
now.

We can't get omit the `idna@0.2.3`, as `trust-dns-proto` hard depend on
it:

```
cargo update -p trust-dns-proto --precise 0.23.2
    Updating crates.io index
error: failed to select a version for the requirement `trust-dns-proto = "^0.21.2"`
candidate versions found which didn't match: 0.23.2
location searched: crates.io index
required by package `check-if-email-exists v0.9.1`
    ... which satisfies dependency `check-if-email-exists = "^0.9.1"` (locked to 0.9.1) of package `lychee-lib v0.18.0 (/home/user/lychee/lychee-lib)`
    ... which satisfies path dependency `lychee-lib` (locked to 0.18.0) of package `lychee v0.18.0 (/home/user/lychee/lychee-bin)`
```

Advisory will be submitted.

Signed-off-by: Dentrax <furkan.turkal@chainguard.dev>