drop py3-asynctest
An attempt to use py3-asynctest with 'import asynctest'
with python3.12 raises an attribute error:

   AttributeError: module 'asyncio' has no attribute 'coroutine'.
   Did you mean: 'coroutines'?

Nothing uses this and upstream does not have commits in 5 years.